repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.12.0
    hooks:
      - id: ruff
        args: [--fix]
      - id: ruff-format

  - repo: local
    hooks:
      - id: pytest-check
        name: pytest-check
        entry: bash -c 'source venv/bin/activate && python -m pytest tests/ -v'
        language: system
        pass_filenames: false
        always_run: true