repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.12.0
    hooks:
      - id: ruff
        args: [src/, tests/, gui/]
      - id: ruff-format
        args: [--check, src/, tests/, gui/]

  - repo: local
    hooks:
      - id: pytest-check
        name: pytest-check
        entry: bash -c 'source venv/bin/activate && python -m pytest tests/ -v --tb=short --ignore=tests/test_documents.py --ignore=tests/test_vectorstore.py'
        language: system
        pass_filenames: false
        always_run: true